---
name: build

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

jobs:
  build:
    strategy:
      # Note, the following build matrix generates jobs that are blocking via prow.
      # When changing the versions or images below, please update prow config too:
      # https://github.com/kubernetes/test-infra/blob/566fea31f63670f583dde93b55fcb0a13bdc2562/config/prow/config.yaml
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        go: [1.13, 1.14]
        exclude:
          - os: macos-10.15
            go: 1.14
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make nodeup examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make nodeup examples test

  verify:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        go: [1.13]
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make travis-ci
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make travis-ci
